import type { Dashboard, PlanRow } from '../types/api';

import { accounts } from './fixtures';

/**
 * The dashboard payload for August 2026, derived from the prototype's own
 * `state` block and its own arithmetic.
 *
 * The planned figures are BR-10 counts against a real August: a weekly plan
 * anchored 05-01-2026 lands five times, one anchored 07-01-2026 lands four.
 * Using the prototype's numbers means a page can be held against the design.
 */

const earnings: readonly PlanRow[] = [
  {
    categoryId: 'freelance',
    category: 'Freelance design',
    type: 'EARNING',
    group: 'Self-employed',
    planned: 120000,
    real: 101000,
    variance: -19000,
    varianceTone: 'BAD',
    perOccurrence: 120000,
    frequency: 'MONTHLY',
    occurrencesInPeriod: 1,
    monthlyEquivalent: 120000,
    derived: false,
    paidWith: null,
    dueNote: null,
    foreignAmount: 'USD 456.00',
  },
  {
    categoryId: 'cafe',
    category: 'Part-time café',
    type: 'EARNING',
    group: 'Employment',
    planned: 64000,
    real: 67200,
    variance: 3200,
    varianceTone: 'GOOD',
    perOccurrence: 16000,
    frequency: 'WEEKLY',
    occurrencesInPeriod: 4,
    monthlyEquivalent: 69333,
    derived: false,
    paidWith: null,
    dueNote: null,
    foreignAmount: null,
  },
  {
    categoryId: 'tutoring',
    category: 'Tutoring',
    type: 'EARNING',
    group: 'Self-employed',
    planned: 22500,
    real: 12000,
    variance: -10500,
    varianceTone: 'BAD',
    perOccurrence: 4500,
    frequency: 'WEEKLY',
    occurrencesInPeriod: 5,
    monthlyEquivalent: 19500,
    derived: false,
    paidWith: null,
    dueNote: null,
    foreignAmount: null,
  },
  {
    categoryId: 'refunds',
    category: 'Refunds & sales',
    type: 'EARNING',
    group: 'Occasional',
    planned: 0,
    real: 6450,
    variance: 6450,
    varianceTone: 'GOOD',
    perOccurrence: 0,
    frequency: 'MONTHLY',
    occurrencesInPeriod: 1,
    monthlyEquivalent: 0,
    derived: false,
    paidWith: null,
    dueNote: null,
    foreignAmount: null,
  },
];

const expenses: readonly PlanRow[] = [
  {
    categoryId: 'rent',
    category: 'Rent',
    type: 'EXPENSE',
    group: 'Fixed',
    planned: 78000,
    real: 78000,
    variance: 0,
    varianceTone: 'NEUTRAL',
    perOccurrence: 78000,
    frequency: 'MONTHLY',
    occurrencesInPeriod: 1,
    monthlyEquivalent: 78000,
    derived: false,
    paidWith: 'Revolut Current',
    dueNote: 'due 01-09',
    foreignAmount: null,
  },
  {
    categoryId: 'groceries',
    category: 'Groceries',
    type: 'EXPENSE',
    group: 'Variable',
    planned: 30000,
    real: 31840,
    variance: 1840,
    varianceTone: 'BAD',
    perOccurrence: 6000,
    frequency: 'WEEKLY',
    occurrencesInPeriod: 5,
    monthlyEquivalent: 26000,
    derived: false,
    paidWith: 'Visa ·· 4417',
    dueNote: null,
    foreignAmount: null,
  },
  {
    categoryId: 'transport',
    category: 'Transport',
    type: 'EXPENSE',
    group: 'Variable',
    planned: 10500,
    real: 7420,
    variance: -3080,
    varianceTone: 'GOOD',
    perOccurrence: 2100,
    frequency: 'WEEKLY',
    occurrencesInPeriod: 5,
    monthlyEquivalent: 9100,
    derived: false,
    paidWith: 'Wallet',
    dueNote: null,
    foreignAmount: null,
  },
  {
    categoryId: 'subscriptions',
    category: 'Subscriptions',
    type: 'EXPENSE',
    group: 'Fixed',
    planned: 4500,
    real: 4498,
    variance: -2,
    varianceTone: 'GOOD',
    perOccurrence: 4500,
    frequency: 'MONTHLY',
    occurrencesInPeriod: 1,
    monthlyEquivalent: 4500,
    derived: false,
    paidWith: 'Visa ·· 4417',
    dueNote: 'due 03-09',
    foreignAmount: 'USD 12.99',
  },
  {
    categoryId: 'card-instalments',
    category: 'Card instalments',
    type: 'EXPENSE',
    group: 'Debt',
    planned: 18574,
    real: 18574,
    variance: 0,
    varianceTone: 'NEUTRAL',
    perOccurrence: 18574,
    frequency: 'MONTHLY',
    occurrencesInPeriod: 1,
    monthlyEquivalent: 18574,
    derived: true,
    paidWith: 'Visa ·· 4417',
    dueNote: 'due 05-09',
    foreignAmount: null,
  },
  {
    categoryId: 'loan-repayments',
    category: 'Loan repayments',
    type: 'EXPENSE',
    group: 'Debt',
    planned: 21840,
    real: 21840,
    variance: 0,
    varianceTone: 'NEUTRAL',
    perOccurrence: 21840,
    frequency: 'MONTHLY',
    occurrencesInPeriod: 1,
    monthlyEquivalent: 21840,
    derived: true,
    paidWith: 'Revolut Current',
    dueNote: null,
    foreignAmount: null,
  },
];

export const dashboard: Dashboard = {
  period: { kind: 'MONTH', from: '2026-08-01', to: '2026-08-31', label: 'August 2026' },
  position: {
    // BR-1: 2,412.30 available against 3,767.88 owed. Negative, as BR-1 allows.
    totalMoneyNow: -135558,
    availableNow: 241230,
    owed: 376788,
    owedOnCards: 38640,
    owedOnInstalments: 83188,
    owedOnLoans: 254960,
    borrowed: 0,
  },
  earnings,
  expenses,
  totals: {
    earningsPlanned: 206500,
    earningsReal: 186650,
    expensesPlanned: 163414,
    expensesReal: 162172,
    netPlanned: 43086,
    netReal: 24478,
  },
  upcoming: [
    {
      key: 'rent',
      label: 'Rent',
      detail: 'Revolut Current · planned',
      date: '2026-09-01',
      amount: -78000,
    },
    {
      key: 'visa-bill',
      label: 'Visa card payment',
      detail: 'statement closed 25-08',
      date: '2026-09-05',
      amount: -38640,
    },
    {
      key: 'cafe-wages',
      label: 'Café wages',
      detail: 'Part-time café · planned',
      date: '2026-09-05',
      amount: 16800,
    },
  ],
  categorySpend: [
    {
      categoryId: 'rent',
      label: 'Rent',
      real: 78000,
      planned: 78000,
      percentOfLargest: 100,
      plannedPercentOfLargest: 100,
    },
    {
      categoryId: 'groceries',
      label: 'Groceries',
      real: 31840,
      planned: 30000,
      percentOfLargest: 41,
      plannedPercentOfLargest: 38,
    },
  ],
  accounts,
};
